kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: dgrechka/node-with-chromium-build-agent:2021090804
  commands:
  - yarn install --pure-lockfile
  # the chromium does not run with root privileges. thus switching to node user
  - sudo -u node yarn run build